In [9]:
import numpy as np
arr = np.arange(6)
print(arr)
print(arr.dtype)


[0 1 2 3 4 5]
int32


In [13]:
arr = np.array([1.5,2.6,3.7])
if arr.dtype == np.float64:
    print("The array is of type float64")
else:
    print("The array is not a type float64")

The array is of type float64


In [17]:
import numpy as np
arr = np.array([1+2j,3+4j,5+6j], dtype=np.complex128)
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


In [25]:
import numpy as np
arr  = np.array([1, 2, 3, 4])
arr_float = arr.astype(np.float32)

In [6]:
import numpy as np
arr = np.array([1.23456789,2.334567891,3.45678912], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print(arr_float32)

[1.2345679 2.3345678 3.456789 ]


In [12]:
import numpy as np
def array_attribute(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype
arr = np.array([[1,2,3], [4, 5, 6]])
result = array_attribute(arr)
print(result)

((2, 3), 6, dtype('int32'))


In [20]:
import numpy as np
def array_dimension(arr):
    return arr.ndim
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2], [3, 4]])
arr3 = np.array([[[1], [2]], [[3], [4]]])
print(array_dimension(arr1))
print(array_dimension(arr2))
print(array_dimension(arr3))      
    

1
2
3


In [22]:
import numpy as np
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size
arr = np.array([1, 2, 3, 4])
size_info = item_size_info(arr)
print(size_info)

(4, 16)


In [26]:
import numpy as np
def array_strides(arr):
    return arr.strides
array = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(array)
print(strides)

(12, 4)


In [30]:
import numpy as np
def shape_stride_relationship(arr):
    shape = arr.shape
    strides = arr.strides
    return shape, strides
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)
print("shape:",shape)
print("strides:",strides)

shape: (2, 3)
strides: (12, 4)


In [34]:
import numpy as np
def create_zeros_array(n):
    zeros_array = np.zeros(n)
    return zeros_array
arr = create_zeros_array(5)
print(arr)

[0. 0. 0. 0. 0.]


In [56]:
import numpy as np
def create_ones_matrix(rows,cols):
    return np.ones((rows,cols))
result = create_ones_matrix(3, 4)
print(result)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [58]:
import numpy as np
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)
result = generate_range_array(0, 10, 2)
print(result)

[0 2 4 6 8]


In [64]:
def generate_linear_space(start, stop, num):
 import numpy as np
 return np.linspace(start, stop, num)
result = generate_linear_space(1.0, 10.0, 5)
print(result)


[ 1.    3.25  5.5   7.75 10.  ]


In [66]:
import numpy as np
def create_identify_matrix(n):
    return np.eye(n)
result = create_identify_matrix(3)
print(result)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [68]:
import numpy as np
def list_to_array(py_list):
    return np.array(py_list)
my_list = [1, 2, 3, 4, 5]
my_array = list_to_array(my_list)
print(my_array)

[1 2 3 4 5]


In [72]:
import numpy as np
original_array = np.array([1, 2, 3, 4, 5])
array_view = original_array.view()
array_view[0] = 99
print("original Array:",original_array)
print("Array View:",array_view)

original Array: [99  2  3  4  5]
Array View: [99  2  3  4  5]


In [78]:
import numpy as np
def concatenate_arrays(array1,array2,axis):
 return np.concatenate((array1, array2), axis=axis)
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6]])
result = concatenate_arrays(array1, array2, axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]]


In [84]:
import numpy as np
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7,8]])
result = np.concatenate((array1, array2.T), axis=1)
print(result)

[[1 2 3 7]
 [4 5 6 8]]


In [90]:
import numpy as np
def stack_vertically(arrays):
    return np.vstack(arrays)
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
c = np.array([[9,10], [11,12]])
arrays = [a, b, c]
stacked_array = stack_vertically(arrays)
print(stacked_array)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [92]:
import numpy as np
def create_array(start, end, step):
    return np.arange(start,end + 1, step)
print(create_array(1, 10, 2))

[1 3 5 7 9]


In [111]:
import numpy as np
def generate_equally_spaced_array():
    return np.linspace(0, 1, 10)
print(np.linspace(0, 1, 10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [113]:
import numpy as np
values=np.logspace(0, 3, 5)
print(values)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [115]:
import numpy as np
import pandas as pd
data = np.random.randint(1, 101,size=(5,3))
df = pd.DataFrame(data, columns=['A', 'B', 'C'])
print(df)

    A   B   C
0  52  60  23
1  24  51  72
2  75  97  48
3  60  85  52
4  65  47   6


In [121]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'A':[1, -2, 3, -4], ' B':[5, -6, 7, -8]})
def replace_negatives_with_zero(df,column_name):
    df[column_name] = np.where(df[column_name] <0, 0, df[column_name])
    return df
df = replace_negatives_with_zero(df,'A')
print(df)

   A   B
0  1   5
1  0  -6
2  3   7
3  0  -8


In [123]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]
print(third_element)

30


In [135]:
import numpy as np
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
element = arr_2d[1,2]
print(element)

6


In [141]:
import numpy as np
arr = np.array([3, 8,2, 10, 5, 7])
condition = arr > 5
condition = [False, True, False, True, False, True]
result= arr[condition]
result = [8, 10, 7]
print(result)

[8, 10, 7]


In [143]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5,6,7,8,9])
sliced_arr = arr[2:6]
print(sliced_arr)

[3 4 5 6]


In [145]:
import numpy as np
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
sub_array = arr_2d[1:3, 1:3]
print(sub_array)
                

[[5 6]
 [8 9]]


In [153]:
import numpy as np
def extract_elements(array_2d, indices):
    rows,cols = zip(*indices)
    extracted_elements = array_2d[rows, cols]
    return extracted_elements
array_2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
indices = [(0, 0), (1, 1), (2, 2)]
result = extract_elements(array_2d, indices)
print(result)

[1 5 9]


In [155]:
import numpy as np
def filter_greater_than_threshold(arr, threshild):
    boolean_mask = arr > threshold
    filtered_elements = arr[boolean_mask]
    return filtered_elements
arr = np.array([1, 5, 8, 2, 9, 4])
threshold = 4
result = filter_greater_than_threshold(arr, threshold)
print(result)


[5 8 9]


In [195]:
import numpy as np
arr = np.array([[[1,2,3], [4,5,6]],
                [[7,8,9],[10,11,12]],
                [[13,14,15],[16,17,18]]])
i_indices= np.array([0, 1, 2])
j_indices= np.array([1, 0, 1])
k_indices= np.array([2, 1, 0])
def extract_elements(arr, i_indices, j_indices, k_indices):
    return arr[i_indices, j_indices, k_indices]
result = extract_elements(arr, i_indices, j_indices, k_indices)
print(result)
                 

[ 6  8 16]


In [197]:
import numpy as np
def filter_array(arr):
    condition1 = arr > 5
    condition2 = arr < 10
    combined_condition = condition1 & condition2
    result = arr[combined_condition]
    return result
arr = np.array([1, 6, 8, 10, 12])
filtered_elements = filter_array(arr)
print(filtered_elements)

[6 8]


In [223]:
import numpy as np
def extract_elesments(array, row_indices, col_indices):
    row_indices = np.asarray(row_indices)
    col_indices = np.asrray(col_indices)
    if len(row_indices) != len(col_indices):
        raise ValueError("row_indices and col_indices must have the same length")
        extracted_elements = array[row_indices, col_indices]
        return extraacted_elements
array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 0, 2])
result = extract_elements(array, row_indices, col_indices)
print(result)
    

None


In [227]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = arr + 5
print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [241]:
import numpy as np
arr1 = np.array([[2, 3, 4]])
arr2 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
result = arr2 * arr1.T
print(result)


[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [243]:
import numpy as np
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])
result = (arr2.T + arr1).T
print(result)

[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [245]:
import numpy as np
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])
result = arr1 + arr2
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [249]:
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1,2], [3,4]])
arr2_reshaped = arr2[:, :, np.newaxis]
result = arr1 * arr2_reshaped
print(result)

[[[ 1  2  3]
  [ 8 10 12]]

 [[ 3  6  9]
  [16 20 24]]]


In [251]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_mean = np.mean(arr, axis=0)
print(column_mean)

[2.5 3.5 4.5]


In [255]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_values = np.max(arr, axis=1)
print(max_values)

[3 6]


In [259]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_indices = np.argmax(arr, axis=0)
print(max_indices)

[1 1 1]


In [263]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
moving_sum = np.cumsum(arr, axis=1)
print(moving_sum)

[[ 1  3  6]
 [ 4  9 15]]


In [267]:
import numpy as np
arr = np.array([[2, 4, 6], [3, 5, 7]])
even_mask = arr % 2 ==0
result = np.all(even_mask, axis=0)
print(result)

[False False False]


In [273]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6,7,8,9])
reshaped_arr = arr.reshape(3,3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [275]:
import numpy as np
def flatten_matrix(matrix):
    return matrix.flatten()
input_matrix = np.array([[1,2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)

[1 2 3 4 5 6]


In [277]:
import numpy as np
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
result = np.concatenate((array1, array2), axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [279]:
import numpy as np
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
def split_array(array, num_splits, axis):
    return np.split(array, num_splits, axis=axis)
sub_arrays_axis0 = split_array(original_array, 3, axis=0)
print(sub_arrays_axis0)
sub_arrays_axis1 = split_array(original_array, 3, axis=1)
print(sub_arrays_axis1)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [285]:
import numpy as np
def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    array_list = original_array.tolist()
    for index, value in zip(indices_to_insert, values_to_insert):
        array_list.insert(index,value)
        modified_array = np.array(array_list)
        indices_to_delete_sorted = sorted(indices_to_delete, reverse=True)
        for index in indices_to_delete_sorted:
            if 0 <=index < len(modified_array):
                modified_array = np.delete(modified_array, index)
                return modified_array
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
result = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result)

[ 1  2 10  4  5]


In [295]:
import numpy as np
arr1 = np.random.randint(1, 100, size=(3, 3))
print("arr1:")
print(arr1)
arr2 = np.arange(1, 10).reshape(3,3)
print("arr2:")
print(arr2)
result = arr1 + arr2
print("Result of element_wise addition:")
print(result)

arr1:
[[ 5 98 57]
 [67 52 46]
 [64 70 61]]
arr2:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Result of element_wise addition:
[[  6 100  60]
 [ 71  57  52]
 [ 71  78  70]]


In [297]:
import numpy as np
arr1 = np.arange(10, 0, -1)
print("arr1:")
print(arr1)
arr2 = np.arange(1, 11)
print("arr2::")
print(arr2)
result = arr1 - arr2
print("Result of element_wise subtration:")
print(result)

arr1:
[10  9  8  7  6  5  4  3  2  1]
arr2::
[ 1  2  3  4  5  6  7  8  9 10]
Result of element_wise subtration:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [299]:
import numpy as np
arr1 = np.random.randint(0, 10, size=(3, 3))
arr2 = np.array([[1, 2, 3], [4, 5, 1], [2, 3, 4]])
result = arr1 * arr2
print("arr1:\n", arr1)
print("arr2:\n",arr2)
print("Result of element -wise multiplication:\n",result)

arr1:
 [[2 5 4]
 [3 0 0]
 [4 5 3]]
arr2:
 [[1 2 3]
 [4 5 1]
 [2 3 4]]
Result of element -wise multiplication:
 [[ 2 10 12]
 [12  0  0]
 [ 8 15 12]]


In [301]:
import numpy as np
arr1 = np.array([2, 4, 6, 8, 10])
arr2 = np.array([1, 2, 3, 4, 5])
result = arr1 / arr2
print(result)

[2. 2. 2. 2. 2.]


In [303]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
result = arr1 ** arr2
print(result)

[ 1 16 27 16  5]


In [307]:
import numpy as np
def count_substring(arr, substring):
    counts = np.char.count(arr, substring)
    total_count = np.sum(counts)
    return total_count
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
print(count_substring(arr,substring))

3


In [328]:
import numpy as np
def extract_uppercase(arr):
    uppercase_chars = []
    for string in arr:
        for char in string:
            if char.isupper():
                uppercase_chars.append(char)
    return np.array(uppercase_chars)
arr = np.array(['Hello', 'Worl', 'OpenAI', 'GPT'])
result = extract_uppercase(arr)
print(result)

['H' 'W' 'O' 'A' 'I' 'G' 'P' 'T']


In [332]:
import numpy as np
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
new_arr = np.char.replace(arr, 'apple', 'orange')
print(new_arr)

['orange' 'banana' 'grape' 'pineorange']


In [336]:
import numpy as np
arr1 = np.array(['Hello', 'world'])
arr2 = np.array(['Open', 'AI'])
result = np.char.add(arr1, arr2)
print(result)

['HelloOpen' 'worldAI']


In [1]:
import numpy as np
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
lengths = np.array([len(s) for s in arr])
max_length = np.max(lengths)
print(max_length)

9


In [5]:
import numpy as np
dataset = np.random.randint(1, 1001, size=100)
mean = np.mean(dataset)
median =  np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)
print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Vaiance: {variance}")
print(f"Standad Deviation: {std_deviation}")

Mean: 535.11
Median: 560.5
Vaiance: 101958.21789999999
Standad Deviation: 319.3089693384763


In [37]:
import random
random_numbers = [random.randint(1, 100) for _ in range(50)]
print(random_numbers)
import numpy as np
random_numbers = [random.randint(1,100) for _ in range(50)]
percentile_25 = np.percentile(random_numbers, 25)
percentile_75 = np.percentile(random_numbers, 75)
print(f"25th Percentile: {percentile_25}")
print(f"75th Percentile: {percentile_75}")
                              

[2, 44, 49, 39, 94, 38, 45, 59, 80, 38, 56, 72, 61, 39, 47, 95, 66, 50, 2, 8, 23, 28, 35, 21, 84, 32, 52, 71, 83, 1, 38, 30, 20, 58, 3, 12, 51, 83, 68, 41, 57, 94, 51, 60, 59, 36, 95, 49, 97, 29]
25th Percentile: 20.5
75th Percentile: 64.75


In [39]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([2, 4, 6, 8, 10])
correlation_matrix = np.corrcoef(array1, array2)
print(correlation_matrix)

[[1. 1.]
 [1. 1.]]


In [43]:
import numpy as np
A = np.array([[1, 2],
             [3, 4]])
B = np.array([[5, 6],
            [7, 8]])
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


In [63]:
import numpy as np
array = np.random.randint(10, 1001, size=50)
array.sort()
percentile_10 = np.percentile(array, 10)
percentile_50 = np.percentile(array, 50)
percentile_90 = np.percentile(array, 90)
quartile_1= np.percentile(array, 25)
quartile_3 =np.percentile(array, 75)

print(f"10th percentile: {percentile_10}" )
print(f"50th percentile (median): {percentile_50}")
print(f"90th perccentile: {percentile_90}")
print(f" First Quartile (Q1): {quartile_1}")
print(f" Third Quratile (Q3): {quartile_3}")


10th percentile: 79.00000000000001
50th percentile (median): 537.5
90th perccentile: 895.1
 First Quartile (Q1): 223.0
 Third Quratile (Q3): 738.5


In [65]:
import numpy as np
array =np.array([10, 20, 30, 40, 50])
index = np.where(array == 30)[0][0]
print("Index of 30:", index)

Index of 30: 2


In [69]:
import numpy as np
random_array = np.random.randint(0, 100, size=10)
print("Random Array:", random_array)
sorted_array = np.sort(random_array)
print("Sorted Array:", sorted_array)

Random Array: [10 42 38 45 68 20 42 67 75 61]
Sorted Array: [10 20 38 42 42 45 61 67 68 75]


In [75]:
import numpy as np
arr = np.array([12,  25, 6, 42, 8, 30])
filtered_arr = arr[arr > 20]
print(filtered_arr)

[25 42 30]


In [79]:
import numpy as np
arr = np.array([1, 5, 8, 12, 15])
mask = arr % 3 == 0
filtered_arr = arr[mask]
print(filtered_arr)

[12 15]


In [83]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
condition = (arr >= 20) & (arr <= 40)
filtered_arr = arr[condition]
print(filtered_arr)

[20 30 40]


In [85]:
import numpy as np
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print(byte_order)

=


In [95]:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
print("Original array:", arr)
arr.byteswap(inplace=True)
print("Array after beswap:",arr)


Original array: [1 2 3]
Array after beswap: [16777216 33554432 50331648]


In [101]:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr.newbyteorder()
print("Original array:", arr)
print("Swapped byte order array:", swapped_arr)

Original array: [1 2 3]
Swapped byte order array: [16777216 33554432 50331648]


In [111]:
import numpy as np
arr = np.array([1, 2, 3], dtype = np.int32)
print(f"Original byte order: {arr. dtype.byteorder}")
if arr.dtype.byteorder == '=': 
    swapped_ar = arr.newbyteorder('>')
    print(f"Swapped byte  order: {swapped_arr.dtype.byteorder}")
else:
    swapped_arr = arr
print(f"Original array: {arr}")
print(f"Array after conditional byte swap : {swapped_arr}")

Original byte order: =
Swapped byte  order: >
Original array: [1 2 3]
Array after conditional byte swap : [16777216 33554432 50331648]


In [113]:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
print("Byte order of the array's dtype:", arr.dtype.byteorder)

Byte order of the array's dtype: =


In [115]:
import numpy as np
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 99
print("arr1:", arr1)
print("copy_arr:", copy_arr)

arr1: [ 1  2  3  4  5  6  7  8  9 10]
copy_arr: [99  2  3  4  5  6  7  8  9 10]


In [119]:
import numpy as np
matrix = np.random.randint(0, 10, (3, 3))
view_slice = matrix[1:3, 1:3]
view_slice[0,0] = 999
print(matrix)

[[  1   0   2]
 [  9 999   4]
 [  6   0   3]]


In [123]:
import numpy as np
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:2, :2]
view_b += 5
print(array_a)

[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]


In [127]:
import numpy as np
orig_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
reshaped_view = orig_array.reshape((4, 2))
reshaped_view[0, 0]= 99
print(orig_array)

[[99  2  3  4]
 [ 5  6  7  8]]


In [129]:
import numpy as np
data = np.random.randint(1, 10, size=(3, 4))
data_copy = data[data > 5]
data_copy[0] = 99
print("original data:\n", data)
print("Modified copy:\n", data_copy)

original data:
 [[4 2 4 4]
 [1 6 3 5]
 [9 6 4 7]]
Modified copy:
 [99  9  6  7]


In [163]:
 A =     [
         [1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]
 ]
B  =      [ 
          [9, 8, 7],
          [6, 5, 4],
          [3, 2, 1]
]

C = [[A[i][j] + B[i][j] for j in range(len(A[0]))] for i in range(len(A))]
D = [[A[i][j] - B[i][j] for j in range(len(A[0]))] for i in range(len(A))]
print("Matrix A:")
for row in A:
    print(row)
print("\nMatrix B:")
for row in B:
    print(row)
print("\nMatrix C (A + B):")
for row in C:
    print(row)
print("\nMatrix D (A - B):")
for row in D:
    print(row)

Matrix A:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

Matrix B:
[9, 8, 7]
[6, 5, 4]
[3, 2, 1]

Matrix C (A + B):
[10, 10, 10]
[10, 10, 10]
[10, 10, 10]

Matrix D (A - B):
[-8, -6, -4]
[-2, 0, 2]
[4, 6, 8]


In [157]:
import numpy as np
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])
D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])
result = np.dot(C, D)
print("Matrix C:")
print(C)
print("\nMatrix D:")
print(D)
print("\nResult of C*D:")
print(result)


Matrix C:
[[1 2]
 [3 4]
 [5 6]]

Matrix D:
[[ 7  8  9 10]
 [11 12 13 14]]

Result of C*D:
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [141]:
import numpy as np
E = np.array([[1, 2, 3],
              [4, 5, 6]])
E_transpose = np.transpose(E)
print("Matrix E:")
print(E)
print("Transpose of Matrix E:")
print(E_transpose)

Matrix E:
[[1 2 3]
 [4 5 6]]
Transpose of Matrix E:
[[1 4]
 [2 5]
 [3 6]]


In [151]:
import numpy as np
F = np.array([[1, 2, 3], [0, 4, 5], [7, 8, 9]])
determinant = np.linalg.det(F)
print(determinant)

-17.999999999999996


In [153]:
import numpy as np
G = np.array([[4, 7, 2],
              [3, 6, 1],
              [2, 5, 3]])
G_inv = np.linalg.inv(G)
print("Orignal Matrix G:")
print(G)
print("\nInverse of Matrix G:")
print(G_inv)
identity_matrix = np.dot(G, G_inv)
print("\nG * G_inv (Should be the Identity Matrix):")
print(identity_matrix)

Orignal Matrix G:
[[4 7 2]
 [3 6 1]
 [2 5 3]]

Inverse of Matrix G:
[[ 1.44444444 -1.22222222 -0.55555556]
 [-0.77777778  0.88888889  0.22222222]
 [ 0.33333333 -0.66666667  0.33333333]]

G * G_inv (Should be the Identity Matrix):
[[ 1.00000000e+00 -2.22044605e-16 -1.11022302e-16]
 [-6.10622664e-16  1.00000000e+00  5.55111512e-17]
 [ 0.00000000e+00  4.44089210e-16  1.00000000e+00]]
